### ISSUE TITLE
 CorDist function missing

### ISSUE THREAD

**Issue by oyxf** [califano-lab/PISCES#13]
Hi,  I can not find the CorDist function in latest updated version, remove it or change its name ?  Thank you

**Comment by GGGGGHua** [comment]
> 
I hadn't found it too.

**Comment by oyxf** [comment]
> > 
> 
> I hadn't found it too.

I read the commit info,  the author is refactoring  the package . I revert  the package to the 2022-02-19 version , reinstall, and it works. Maybe you can try it in the same way .

**Comment by lvlahos343** [comment]
Hey all - we're currently in the midst of a big re-design for the whole package, one that incorporates new advances our lab has made in terms of both the core methodologies and ideal workflows.

In the current version, the `CorDist` function has been replaced by `cor_dist`.
